#!/bin/bash

. ${SCRIPTS:-/}start-utils

if [[ $SSH ]]; then
  if isTrue "$SSH"; then
    if [[ $SSH_PASS ]] && [[ $SSH_USER ]]; then
		sudo useradd -p $(openssl passwd -crypt $SSH_PASS) -d "/data" $SSH_USER
	else
		sudo useradd -p $(openssl passwd -crypt "pass") -d "/data" "user"
	fi

	mkdir -p /var/run/sshd
	/usr/sbin/sshd
  fi
fi
